<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'IBNet Blog - Coming Soon!';
Url::remember();
?>
<div class="site-about">
    <h1><?= $this->title ?></h1>

    <div class="media">
        <div class="media-body">

            <p>We want IBNet to serve as a forum for the exchange of information, wisdom, and ideas among independent Baptists.  We will achieve this in part by hosting written content generated by our users in the form of a new blog.  We are looking for original, informative, impactful, timely, biblically-based essays written by our users for digest by the broader independent Baptist community.  The subject matter could relate to any area that is relevant to the faith and practice of Baptists.  The limitation is your own imagination (and prudence).  Look for the launch of our new blog shortly!</p>

        </div>
        <div class="media-right">
            <?= HTML::img('@web/images/blog-coming-soon-lg.jpg', ['class' => 'media object', 'style' => 'margin-left: 10pt']) ?>
        </div>
    </div>

    <p>&nbsp;</p>

</div>
